version: '3'

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - '2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    volumes:
      - ./data/zookeeper_data:/bitnami/zookeeper
    networks:
      - kafka-cluster1

  kafka-0:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - '9093:9093'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_BROKER_ID: '0'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      # kafdorp과 연동하려면 INTERNAL 옵션이 중요하다
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'CLIENT://:9092,EXTERNAL://:9093'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'CLIENT://kafka-0:9092,EXTERNAL://${host_ip}:9093'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'CLIENT'
    volumes:
      - ./data/kafka_0_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster1

  kafka-1:
    image: docker.io/bitnami/kafka:3.1
    ports:
      - '9094:9094'
    environment:
      KAFKA_CFG_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_CFG_BROKER_ID: '1'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: 'CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT'
      KAFKA_CFG_LISTENERS: 'CLIENT://:9092,EXTERNAL://:9094'
      KAFKA_CFG_ADVERTISED_LISTENERS: 'CLIENT://kafka-1:9092,EXTERNAL://${host_ip}:9094'
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: 'CLIENT'
    volumes:
      - ./data/kafka_1_data:/bitnami/kafka
    depends_on:
      - zookeeper
    networks:
      - kafka-cluster1

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: 'no'
    ports:
      # 포트 변경 불가
      - '19000:9000'
    environment:
      # 연결할 브로커 목록
      KAFKA_BROKERCONNECT: 'kafka-0:9092,kafka-1:9092'
      JVM_OPTS: '-Xms16M -Xmx48M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify'
    depends_on:
      - zookeeper
      - kafka-0
      - kafka-1
    networks:
      - kafka-cluster1

networks:
  kafka-cluster1:
    driver: bridge
