version: '3.8'
services:
  azit-pg:
    image: postgres:11.4
    env_file: .env
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init-pg.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    networks:
      - my_network
networks:
  my_network:
